### ISSUE TITLE
Read attributes for route definitions from even more places

### ISSUE THREAD

**Issue by jbretsch** [jbretsch/openapi-route-definition-locator#5]
Attributes for the routes definitions created by the OpenAPI Route Definition Locator can already be set at various places:

1. Globally within each OpenAPI definition.
2. For each operation within an OpenAPI definition.
3. Via `OpenApiRouteDefinitionCustomizer` beans.
4. Via Spring Cloud Gateway `default-filters`.

But people may like to configure those attributes also
1. For each service within the `openapi-route-definition-locator` object, i.e.
    ```yaml
    openapi-route-definition-locator:
      services:
        - id: service1
          uri: http://service1:8080
          # Here.
    ```
2. Globally for all routes created by the OpenAPI Route Definition Locator but no other registered `RouteDefinitionLocator`.
    ```yaml
    openapi-route-definition-locator:
      # Here.
      services:
        - id: service1
          uri: http://service1:8080
    ```
